# Generated by Django 5.1.1 on 2025-04-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescore',
            name='game_type',
            field=models.CharField(choices=[('anagram', 'Anagram Hunt'), ('math', 'Math Facts')], default='Anagram Hunt', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamescore',
            name='max_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamescore',
            name='operation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='word_length',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
